// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Roupa",
                            Description = "Camiseta Preta Tema Jurasic Park",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/2_no_internet.jpg",
                            Name = "Camiseta Jurasic Park",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Acessório",
                            Description = "Capacete Preto Tema Star Wars",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/3_vader.jpg",
                            Name = "Capacete Darth Vader",
                            Price = 129.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Brinquedo",
                            Description = "Boneco StormTropper - ActionFigure",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/4_storm_tropper.jpg",
                            Name = "StormTropper",
                            Price = 254.8m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Roupa",
                            Description = "Camiseta Preta Tema Gamer",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/5_100_gamer.jpg",
                            Name = "Camiseta Gamer",
                            Price = 29.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Roupa",
                            Description = "Camiseta Branca Tema SpaceX",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/6_spacex.jpg",
                            Name = "Camiseta SpaceX",
                            Price = 59.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Roupa",
                            Description = "Camiseta Creme Tema Café",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/7_coffee.jpg",
                            Name = "Camiseta Coffee",
                            Price = 36.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Roupa",
                            Description = "Moletom Preto Tema Cobra Kai",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/8_moletom_cobra_kay.jpg",
                            Name = "Moletom Cobra Kai",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Livro",
                            Description = "Livro de Ciências Star Talk - Autor: Neil deGrasse Tyson",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/9_neil.jpg",
                            Name = "Livro Star Talk - Neil deGrasse Tyson",
                            Price = 129.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Brinquedo",
                            Description = "Brinquedo Milennium Falcon Tema Star Wars",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/10_milennium_falcon.jpg",
                            Name = "Milennium Falcon",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Roupa",
                            Description = "Camiseta Preta Tema Mars",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/11_mars.jpg",
                            Name = "Camiseta Nerd MARS",
                            Price = 34.9m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Roupa",
                            Description = "Camiseta Branca Tema Linux",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/12_gnu_linux.jpg",
                            Name = "Camiseta Linux",
                            Price = 44.9m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Roupa",
                            Description = "Camiseta Branca Tema Dragon Ball Z",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/13_dragon_ball.jpg",
                            Name = "Camiseta Dragon Ball",
                            Price = 27.9m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "Acessório",
                            Description = "Patch Tema NASA",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/dot_net6_LTS/ShoppingImages/14_patch_nasa.jpg",
                            Name = "Adesivo NASA",
                            Price = 19.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
